version: '2.1'
services:
  orientdb:
    container_name: debattons_orientdb
    build:
      context: ../
      dockerfile: docker/Dockerfile.orientdb.dev
    image: debattons_orientdb
    environment:
      - ORIENTDB_ROOT_PASSWORD=${ORIENTDB_ROOT_PASSWORD}
    volumes:
#      - ${DOCKER_DATA}/orientdb/config:/orientdb/config
      - ${DOCKER_DATA}/orientdb/databases:/orientdb/databases
      - ${DOCKER_DATA}/orientdb/backup:/orientdb/backup
    ports:
      - "${ORIENTDB_PORT:-2424}:2424"
      - "${ORIENTDB_STUDIO_PORT:-2480}:2480"
    restart: ${ORIENTDB_RESTART:-no}
  debattons:
    container_name: debattons_dev
    build:
      context: ../
      dockerfile: docker/Dockerfile.dev
      args:
        - USER_UID
        - USER_GID
        - http_proxy
        - https_proxy
        - HTTP_PROXY
        - HTTPS_PROXY
    image: debattons:dev
    volumes:
      - ${ROOT_PROJECT_DIR}:/opt/debattons
      - ${HOME}/.m2:/home/user/.m2
      - ${HOME}/.npm:/home/user/.npm
      - ${DOCKER_DATA}/orientdb/databases:/opt/orientdb/databases
      - ${DOCKER_DATA}/orientdb/backup:/opt/orientdb/backup
    ports:
      - "4200:4200"
      - "8080:8080"
      - "2424:2424"
      - "2480:2480"
    environment:
      - ORIENTDB_ROOT_PASSWORD=${ORIENTDB_ROOT_PASSWORD}
      - http_proxy
      - https_proxy
      - HTTP_PROXY
      - HTTPS_PROXY
# Comment the following link as current 3.0.0-SNAPSHOT console version is unable to talk to 3.0.0m2 server version, https://github.com/orientechnologies/orientdb/issues/7901
#    links:
#      - orientdb:orientdb
